### ISSUE TITLE
[noRealIssue] you are just working on a project i am also thinking about :-)

### ISSUE THREAD

**Issue by janpauldahlke** [FlixCoder/fhir-sdk#1]
HI there, i am curios about rust and FHIR with typescript background, i was looking around and just came across this repo in which you are actually quite active. Sending regards. How is it going?

**Comment by janpauldahlke** [comment]
I am a rust beginner from Germany, HH. Maybe i can help you in this repo? Kind regards @ Aachen?

**Comment by FlixCoder** [comment]
Hi, so in general contributions are welcome, but I am still in the early stages and quite picky about what I will accept.

Though there are a few things which I don't currently plan to do myself and it would not conflict to work on those an PR them I think. That is mostly XML.
I plan to work on GraphQL at some point, but only after the REST client and plenty other features most likely.

So I would recommend to go for XML or a FHIR GraphQL client for contributions for now :)

**Comment by janpauldahlke** [comment]
if you dont mind and only if you find yourself the time to answer. i tried a little for myself, but you use way more sophisticated techniques. Did you inspected the json itself before so you knew how to iterate over the datastructure to generate `gen_codes` `gen_traits`  in the `` [fhir-sdk](https://github.com/FlixCoder/fhir-sdk/tree/main)/[crates](https://github.com/FlixCoder/fhir-sdk/tree/main/crates)/[generate](https://github.com/FlixCoder/fhir-sdk/tree/main/crates/generate)/[src](https://github.com/FlixCoder/fhir-sdk/tree/main/crates/generate/src)
/generate/ file e.g where this is itself also to be considered an example, no need to go into details here.

**Comment by FlixCoder** [comment]
The JSON is a FHIR resource `StructureDefinition`. The rest I figured out myself I think.
See http://hl7.org/fhir/structuredefinition.html .

Obviously there is some more from the FHIR spec needed, as the JSON representation does not follow to structure definitions, especially with the field extensions.

**Comment by FlixCoder** [comment]
Using the library and pointing out issues would also help by the way :D I did my best to include as much as possible, but especially with the codes (valuesets) I think there might be plenty missing and there is room to improve.

**Comment by janpauldahlke** [comment]
ya, but i want to improve my rust and fhir also :-)) i will try it some time over the wknd
