### ISSUE TITLE
Improve compile time and its resource usage

### ISSUE THREAD

**Issue by FlixCoder** [FlixCoder/fhir-sdk#17]
I want to experiment with my own Serialize/Deserialize implementation to see if that fixes some of it.

**Comment by FlixCoder** [comment]
Switching back to derive_builder made up for a lot of the compile time resources, so now it is mostly serde. But it turns out, there is not too much up for grabs, so unsure whether it can be fixed with a manual serde implementation..

**Comment by fage88** [comment]
Hi @FlixCoder,

Was this closed as a won't do or are there some improvements in the 0.14.1 release?
