### ISSUE TITLE
Examples for loading resources from JSON

### ISSUE THREAD

**Issue by amrit110** [FlixCoder/fhir-sdk#22]
Hi there! I'm trying to use your library. Would really appreciate some examples for reading fhir resources from JSON files.

**Comment by FlixCoder** [comment]
You can just use any serde compatible JSON library like serde_json to deserialize the resource. I do this here for example: https://github.com/FlixCoder/fhir-sdk/blob/main/crates/generate/src/parse/codes.rs#L308

So you can choose any way of reading the file and deserializing.

```rust
let file = File::open("bla.json")?;
let buf_reader = BufReader::new(file);
let resource: Resource = serde_json::from_reader(buf_reader)?;
```

**Comment by FlixCoder** [comment]
Done in https://github.com/FlixCoder/fhir-sdk/commit/4c1a3f507915b1ff08cc39f7a78c97bb24dbe5c1
