### ISSUE TITLE
Missing `history` operation

### ISSUE THREAD

**Issue by skomski** [FlixCoder/fhir-sdk#24]
I cannot seem to find the `history` operation (https://www.hl7.org/fhir/http.html#history). Is the operation not yet implemented?

**Comment by FlixCoder** [comment]
It is not implemented yet, only retrieving a specific version ID from the history is implemented yet

**Comment by skomski** [comment]
Would you accept a PR for it? Are bigger stumbling blocks to be expected? ^^
