### ISSUE TITLE
`ClientBuilder` requires the `auth_callback` to be `Copy`

### ISSUE THREAD

**Issue by Revanee** [FlixCoder/fhir-sdk#27]
The `ClientBuilder` requires the `auth_callback` being passed to be `Copy`. This makes it difficult to manage the credentials being used, as `Copy` closures need to only contain `Copy` references. If we have a `client_id` and `client_secret` as `String`s, they cannot be owned by the function being passed. We also cannot use `Arc` references to them, since `Arc` also isn't `Copy`. The possible workarounds seem to be either using `'static` references, or having to keep track of lifetimes, neither of which is ideal.

I would suggest changing the `Copy` requirement to `Clone`, as this would still allow usage of `Copy` closures, but also allow having credentials owned by the `auth_callback`.

**Comment by FlixCoder** [comment]
Hmm yeah, I expected such a thing at some point. I couldn't figure out how to get rid of the Copy constraint, the closure needs to be duplicated somehow because it is moved into the async block.
Please feel free to try yourself on it as well

**Comment by Revanee** [comment]
Wow that was a quick response! :D I've opened a PR where I use `Clone` to duplicate the closure before calling it.
