### ISSUE TITLE
Derive Hash for ResourceType

### ISSUE THREAD

**Issue by trobanga** [FlixCoder/fhir-sdk#31]
Deriving Hash for ResourceType (and maybe for other structs, too) would allow to use ResourceType as key in a HashMap.

**Comment by FlixCoder** [comment]
Which ResourceType do you mean? The one used across the library to differentiate between resource types etc. is already Hash. Only the generated, extensible one from the FHIR definitions is not, but you are right, they could also derive Hash I guess. I've done that now ^^
