### ISSUE TITLE
How to PATCH a Vector or a single element in a Vector?

### ISSUE THREAD

**Issue by rsansores** [FlixCoder/fhir-sdk#32]
Hello, have checked the tests but can't figure out what's the process to patch a full Vector or a single element in a vector. Is there a way with the current Builder API?

```
                fhir_update = fhir_update.replace(
                "Patient.name",
                ParametersParameter::builder()
                    .name("value".to_owned())
                    .value(ParametersParameterValue::HumanName(
                        HumanName::builder()
                            .given(vec![Some(first_name.to_string())])
                            .family(last_name.to_string())
                            .build()?,
                    ))
                    .build()?,
            );
```
This will replace all the names by the new HumanName provided. Is there a way to replace the whole array providing more than one HumanName? Or better replace one HumanName E.g. by Type? or System?

**Comment by FlixCoder** [comment]
Well, it is just a very raw and generic builder for PATCH requests, up to [the FHIR spec](https://hl7.org/fhir/http.html#patch). I think everything spec compliant should be possible.

However, I didn't use patch too much myself, so I might not be of too much help here, but the official FHIR Zulip chat will definitely help.

In case you are familiar with JSON patch syntax, that is also supported by FHIR and my library, so if you find any resources on how to do it there, it should also be possible here.

I would also expect, that the operations are executed sequentially, so it might be possible to replade the list with one item and then add more items to the list one by one in more operation steps.

There might also be more valid patch examples here: https://github.com/FHIR/fhir-test-cases/releases

**Comment by FlixCoder** [comment]
> Is there a way to replace the whole array providing more than one HumanName? Or better replace one HumanName E.g. by Type? or System?

I am unsure, but I think that's not possible. However, it is possible to read the resource, determine, the array indices and patch the resource according to array indices. A "test" operation in the patch can make sure the value is still where expected.
But the more complicated it gets, the more sense it makes to use conditional-update instead, failing if there were updates to the resource between your read and write.

**Comment by rsansores** [comment]
Thanks a lot for the quick response. By the way. Your library rocks. I will try to contribute in the future when I get more used to FHIR and the internals. Thanks a lot.

**Comment by FlixCoder** [comment]
Seems everything is fine? Closing, feel free to re-open if necessary
