### ISSUE TITLE
Is there a way to search over Bundle resources?

### ISSUE THREAD

**Issue by rsansores** [FlixCoder/fhir-sdk#36]
When calling an Epic resource, e.g. a Procedure. The response gets Bundled. This is an example:

```
{
    "resourceType": "Bundle",
    "type": "searchset",
    "total": 2,
    "link": [
        {
            "relation": "self",
            "url": "https://fhir.epic.com/interconnect-fhir-oauth/api/FHIR/R4/Procedure?patient=erXuFYUfucBZaryVksYEcMg3"
        }
    ],
    "entry": [
        {
            "link": [
                {
                    "relation": "self",
                    "url": "https://fhir.epic.com/interconnect-fhir-oauth/api/FHIR/R4/Procedure/e0ZpcfJHKvPE0nQfie.r1utQLnHC473E7POoGnZIh7yj3wWsggKlPmbROlo9Q5vi-3"
                }
            ],
            "fullUrl": "https://fhir.epic.com/interconnect-fhir-oauth/api/FHIR/R4/Procedure/e0ZpcfJHKvPE0nQfie.r1utQLnHC473E7POoGnZIh7yj3wWsggKlPmbROlo9Q5vi-3",
            "resource": {
                "resourceType": "Procedure",
                "id": "e0ZpcfJHKvPE0nQfie.r1utQLnHC473E7POoGnZIh7yj3wWsggKlPmbROlo9Q5vi-3",
                "identifier": [
                    {
                        "use": "usual",
                        "type": {
                            "text": "ORD"
                        },
                        "system": "urn:oid:1.2.840.114350.1.13.0.1.7.2.798268",
                        "value": "1066915"
                    },.....
```

So the search is like this:

`https://fhir.epic.com/interconnect-fhir-oauth/api/FHIR/R4/Procedure`

But the result is a Bundle that contains the procedure.

```
let procedures: Vec<Procedure> = fhir_client
            .search(SearchParameters::empty())
            .try_collect()
            .await?;
```

This won't work since the response is not decodable into a Procedure. And changing Procedure to Bundle won't work too because then the URL is changed by the SDK into `https://fhir.epic.com/interconnect-fhir-oauth/api/FHIR/R4/Bundle.`

Is there a way to solve this? Maybe I need to create a wrapper struct BundledProcedure or EpicProcedure?

**Comment by FlixCoder** [comment]
If I search for "epic" in the FHIR specification, there is no result. Could you provide a link to the expected behavior in the specification?
Or is this some kind of non-standard interaction?

From what I can see, the Procedure resource is a valid resource to search for and your example resource looks like a normal procedure search response, being a bundle containing a procedure. So it should work right?
So I am afraid I don't understand the problem and need more information.

**Comment by rsansores** [comment]
Damm... you are completly right. I was using the R5 and Epic only supports R4. Sorry for the stupid question and making you lose time.

**Comment by FlixCoder** [comment]
No worries :D Be sure to disable R5 if you only need R4(B) to save some compile time resources and make R4(B) the default version of the client ^^
