### ISSUE TITLE
Allow building without OpenSSL

### ISSUE THREAD

**Issue by drakon64** [FlixCoder/fhir-sdk#45]
Currently the `client` feature adds `reqwest` as a dependency with its default feature set. This adds a dependency on OpenSSL.

I wonder if potentially another feature could be added named `client-rustls` which brings in `reqwest` with native SSL disabled and `rustls-tls` enabled. This would allow building `fhir-sdk` without (or at least with less) native dependencies.

**Comment by FlixCoder** [comment]
I wish it was possible to forward certain features to reqwest without manually specifying all :D But yeah, the solution is to add all the relevant feature flags that reqwest has and forward them. As well as disabling default features on reqwest.

**Comment by drakon64** [comment]
Yeah, I wish there was a better way to handle this.

https://github.com/FlixCoder/fhir-sdk/pull/46 would 'fix' this issue in that the native OpenSSL dependency would be gone, but it would be forced rather than users having the choice.

Granted, I can't imagine it would cause any issues, and surely having less native dependencies is a good thing?
